# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Intro"
license = "MIT"
licenselink = "https://github.com/aisola/intro/blob/master/LICENSE.md"
description = ""
homepage = "https://abramisola.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Abram Isola"
  homepage = "https://abramisola.com"
